name: Build Container Image

on:
  workflow_dispatch:

  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build:
    name: Build Container Image

    uses: your-org/ci-platform/.github/workflows/build-container.yaml@v1

    secrets:
      CI_REGISTRY_USERNAME: ${{ secrets.CI_REGISTRY_USERNAME }}
      CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}

    with:
      image_name: example-image
      dockerfile: Dockerfile
      runner: ci-build