name: Build Test Image

on:
  workflow_dispatch:

  push:
    branches:
      - main

    paths:
      - ".github/workflows/**"
      - "images/test/**"

permissions:
  contents: read

jobs:
  build:
    uses: konkele-homelab/ci-platform/.github/workflows/build-oci-container.yaml@v1

    secrets:
      CI_REGISTRY_USERNAME: ${{ secrets.CI_REGISTRY_USERNAME }}
      CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}

    with:
      image_name: ci-platform-test-image
      dockerfile: images/test/Dockerfile
      runner: ci-build

      extra_tags: |
        type=raw,value=test

  validate:
    needs: build

    uses: konkele-homelab/ci-platform/.github/workflows/validate-oci-container.yaml@v1

    with:
      image_name: ci-platform-test-image
      image_tag: test
      test_command: cat /message.txt

    secrets:
      CI_REGISTRY_USERNAME: ${{ secrets.CI_REGISTRY_USERNAME }}
      CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}