name: Build Test Image

on:
  workflow_dispatch:

  push:
    tags:
      - "v*.*.*"


permissions:
  contents: read


jobs:
  build:
    name: Build Test Image

    uses: ./.github/workflows/build-container.yaml

    with:
      image_name: test-image
      dockerfile: images/test/Dockerfile
      runner: ci-build

      extra_tags: |
        type=raw,value=test

    secrets: inherit


  smoke:
    name: Smoke Test Test Image

    needs:
      - build

    uses: ./.github/workflows/smoke-container.yaml

    with:
      image: ${{ needs.build.outputs.reference }}
      expected_file: /message.txt

    secrets: inherit


  validate:
    name: Validate Test Image

    needs:
      - build
      - smoke

    uses: ./.github/workflows/validate-container.yaml

    with:
      tags: ${{ needs.build.outputs.tags }}

    secrets: inherit